python3 trainEBM.py \
  --ddp \
  --nodes 1 \
  --gpus 8 \
  --nr 0 \
  --port 12282 \
  --model_name="GraphEBM_sep_projBoth_FFout" \
  --encoder_rnn_type gru \
  --atom_pool_type attention \
  --mol_pool_type sum \
  --encoder_hidden_size 300 \
  --encoder_inner_hidden_size 320 \
  --encoder_depth 10 \
  --encoder_dropout 0.08 \
  --proj_hidden_sizes 256 200 \
  --proj_activation "PReLU" \
  --proj_dropout 0.12 \
  --out_hidden_sizes 600 300 \
  --out_activation "PReLU" \
  --out_dropout 0.15 \
  --rxn_smis_file_prefix="50k_clean_rxnsmi_noreagent" \
  --onthefly \
  --do_compute_graph_feat \
  --cache_suffix='50top_200max_stereo' \
  --do_finetune \
  --do_test \
  --do_get_energies_and_acc \
    --log_file=g2e_best/10x300_320_256x200_600x300_SIM_STEREO_50top200max_1e4_fac70_pat3_stop7_80ep_8GPU_${SLURM_JOBID}.log \
	--expt_name=10x300_320_256x200_600x300_SIM_STEREO_50top200max_1e4_fac70_pat3_stop7_80ep_8GPU \
    --proposals_csv_file_prefix="retrosim_200topk_200maxk_noGT" \
	--precomp_file_prefix="" \
	--representation="smiles" \
	--random_seed=0 \
	--batch_size=2 \
    --batch_size_eval=2 \
	--minibatch_size=50 \
	--minibatch_eval=200 \
    --grad_clip=15 \
    --lr_floor_stop_training \
    --lr_floor 1e-8 \
    --lr_cooldown=1 \
    --warmup_epochs 0 \
	--learning_rate=1e-4 \
    --lr_scheduler='ReduceLROnPlateau' \
    --lr_scheduler_factor=0.7 \
    --lr_scheduler_patience=3 \
	--optimizer="Adam" \
	--epochs=80 \
    --early_stop \
    --early_stop_patience=7 \
	--num_workers=0 \
	--checkpoint \
    --test_on_train